# Generated by Django 5.1 on 2024-08-20 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='repositorio',
            name='colaboradores',
            field=models.ManyToManyField(related_name='repositorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositorios_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
