# Generated by Django 2.2.9 on 2024-08-21 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_repositorio_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracao', models.DurationField()),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_publicados', to=settings.AUTH_USER_MODEL)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.Repositorio')),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violencia_ocorreu', models.BooleanField(default=False)),
                ('violencia_contra_mulher', models.BooleanField(default=False)),
                ('duracao_violencia', models.DurationField(blank=True, null=True)),
                ('comeco_violencia', models.TimeField(blank=True, null=True)),
                ('final_violencia', models.TimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='api.Video')),
            ],
        ),
        migrations.CreateModel(
            name='PublicadoEm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Repositorio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video')),
            ],
            options={
                'unique_together': {('video', 'repositorio')},
            },
        ),
    ]
