# Generated by Django 5.1 on 2024-08-24 20:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_analise_id_alter_repositorio_id_alter_video_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='data_publicacao',
            new_name='criado_em',
        ),
        migrations.AlterField(
            model_name='video',
            name='arquivo',
            field=models.FileField(upload_to=api.models.upload_to),
        ),
    ]
