# Generated by Django 5.1 on 2024-08-26 23:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_data_publicacao_video_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.thumbnail_upload_to),
        ),
    ]
