# Generated by Django 5.1 on 2024-08-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
